"""
Created on Jun 24, 2015

@author: joshia7
"""

# class MessageConstants:
"""
Contains all the Messages
"""
MESSAGE_URL_REQUIRED = "URL Required"
MESSAGE_NAMESPACE_ID_REQUIRED = "Namespace ID  Required"
MESSAGE_NAMESPACE_REQUIRED = "Namespace Required"
MESSAGE_CLASSNAME_REQUIRED = "ClassName Required"
MESSAGE_USER_ID_REQUIRED = "User ID Required"
MESSAGE_PERIOD_REQUIRED = "Period Required"
MESSAGE_BLOCKSIZE_REQUIRED = "Blocksize Required"
MESSAGE_NOTIFICATION_SIZE_REQUIRED = "Notification Size Required "
MESSAGE_BUCKET_REQUIRED = "Bucket Required"
MESSAGE_START_TIME_REQUIRED = "Start Time Required"
MESSAGE_END_TIME_REQUIRED = "End Time Required"
MESSAGE_START_TIME_NOT_VALID = "Start Time Not Valid:Should Be Multiple Of 5"
MESSAGE_END_TIME_NOT_VALID = "End Time Not Valid:Should Be Multiple Of 5"
MESSAGE_TOKEN_REQUIRED = "Token Required"
MESSAGE_USERNAME_REQUIRED = "UserName required"
MESSAGE_PASSWORD_REQUIRED = "Password Required"
MESSAGE_DEFAULT_DATA_SERVICE_REQUIRED = "Default Data Services VPool Required"
MESSAGE_UID_REQUIRED = "UID Required"
MESSAGE_SECRET_REQUIRED = "Secret Required"
MESSAGE_METADATA_REQUIRED = "Metadata Required"
MESSAGE_METADATA_INVALID = "Metadata Should be a Dict"
MESSAGE_CLUSTER_ID_REQUIRED = "Cluster Id Required"
MESSAGE_STORAGE_POOL_ID_REQUIRED = "Storage Pool ID Required"
MESSAGE_NODE_INSTANCE_REQUIRED = "Node Instance Required"
MESSAGE_PROCESS_INSTANCE_REQUIRED = "Process Instance Required"
MESSAGE_DISK_ID_REQUIRED = "Disk Id Required"
MESSAGE_REPLICATION_GROUP_IDENTIFIER_REQUIRED = "Replication Group Identifier required"
MESSAGE_MARKER_REQUIRED = "Marker Required"
MESSAGE_LIMIT_REQUIRED = "Limit Required"

MESSAGE_REPLICATION_GROUP_NAME_REQUIRED = "Replication Group Name Required"
MESSAGE_REPLICATION_GROUP_DESCRIPTION_REQUIRED = "Replication Group Description Required"
MESSAGE_ALLOW_ALL_NAMESPACE_REQUIRED = "Indication To Allow All Namespace  Required"
MESSAGE_STORAGE_POOL_NAME_REQUIRED = "Storage Pool Name Required"
MESSAGE_STORAGE_POOL_VALUE_REQUIRED = "Storage Pool Value Required"

MESSAGE_BASE_URL_NAME_REQUIRED = "BaseURL Name Required"
MESSAGE_BASE_URL_VALUE_REQUIRED = "BaseURL  Value Required"
MESSAGE_IS_NAMESPACE_IN_HOST_REQUIRED = "IS NameSpace In Host Required"
MESSAGE_IS_NAMESPACE_IN_HOST_NOT_VALID = "Is NameSpace In Host Should be Boolean"
MESSAGE_BASEURL_IDENTIFIER_REQUIRED = "BaseURL Identifier Required"

MESSAGE_EVENT_ID_REQUIRED = "Event Id Required"
MESSAGE_USER_STRING_REQUIRED = "User String Required"
MESSAGE_CONTACT_REQUIRED = "Contact Required"
MESSAGE_EVENT_ID_NOT_VALID = "Event Id Not Valid"

MESSAGE_BUCKET_NAME_REQUIRED = "Bucket Name required"
MESSAGE_FILESYSTEM_ENABLED_REQUIRED = "Check for File System Enabled Required"
MESSAGE_FILESYSTEM_NOT_VALID = "File System Enabled Information Should be Boolean"
MESSAGE_HEAD_TYPE_REQUIRED = "Head Type Required"
MESSAGE_IS_STALE_ALLOWED_REQUIRED = "Is Stale Allowed Required"
MESSAGE_IS_STALE_NOT_VALID = "Is State Allowed Should be Boolean"

MESSAGE_OWNER_REQUIRED = "New Owner Value Required"
MESSAGE_IS_LOCK_REQUIRED = "Is Lock required"
MESSAGE_IS_LOCK_NOT_VALID = "Value of Is Locked should be boolean"
MESSAGE_ACL_REQUIRED = "ACL Required"
MESSAGE_NODE_ID_REQUIRED = "Node Id Required"
MESSAGE_NODE_NAME_REQUIRED = "Node Name Required"
MESSAGE_VIRTUAL_ARRAY_REQUIRED = "VArray Required"
MESSAGE_NODE_DESCRIPTION_REQUIRED = "Node Description Required"
MESSAGE_DATA_STORE_IDENTIFIER_REQUIRED = "Data Store Identifier Required"
MESSAGE_NODELIST_SHOULD_BE_ARRAY = "Node List Should be Array"
MESSAGE_TASK_OPERATION_ID = "Task Operation Id Required"
MESSAGE_DATA_STORE_ID_ARRAY_REQUIRED = "List of data store Id should be Array"

MESSAGE_VIRTUAL_ARRAY_NAME_REQUIRED = "Virtual Array Name Required"
MESSAGE_IS_PROTECTED_REQUIRED = "Indication If Virtual Array Is Protected Required"
MESSAGE_DESCRIPTION_REQUIRED = "Description Required"
MESSAGE_IS_PROTECTED_SHOULD_BE_BOOLEAN = "IS Protected Should be Boolean"

MESSAGE_VDC_NAME_REQUIRED = "VDC Name Required"
MESSAGE_INTERVDC_END_POINTS_REQUIRED = "End Points Of VDC Required"
MESSAGE_SECRET_KEYS_REQUIRED = "Secret Keys Required"
MESSAGE_VDC_NEW_NAME_REQUIRED = "VDC New Name Required"
MESSAGE_VDC_ID_REQUIRED = "VDC Id Required"

MESSAGE_AUTH_PROVIDER_ID_REQUIRED = "Authentication Provider ID Required"
MESSAGE_AUTH_PROVIDER_REQUIRED = "Authorization Provider Required"

MESSAGE_GROUPS_LIST_REQUIRED = "Group List Required"
MESSAGE_GROUPS_LIST_SHOULD_BE_ARRAY = "Group List Should be Array"

MESSAGE_EXPIRY_TIME_FOR_KEY_REQUIRED = "EXPIRY TIME FOR KEY REQUIRED"

MESSAGE_IS_SYSTEM_ADMIN_REQUIRED = "IS System Admin Info Required"
MESSAGE_IS_SYSTEM_MONITOR_REQUIRED = "Is System Monitor Info Required"
MESSAGE_IS_SYSTEM_ADMIN_SHOULD_BE_BOOLEAN = "Is System Admin Should Be Boolean"
MESSAGE_IS_SYSTEM_MONITOR_SHOULD_BE_BOOLEAN = "Is System Monitor Should Be Boolean"

MESSAGE_TAGS_REQUIRED = "Tags Required"
MESSAGE_TAGS_SHOULD_BE_ARRAY = "Tags should be an Array"
MESSAGE_VARRAYS_SHOULD_BE_DICT = "Varrays should be a Dictionary"

MESSAGE_IS_ALLOW_NAMESPACE_SHOULD_BE_BOOLEAN = "Is Allow Namespace Should Be Boolean"
MESSAGE_ZONE_MAPPINGS_SHOULD_BE_DICT = "Zone Mappings Should Be Dictionary"
MESSAGE_ZONE_MAPPINGS_REQUIRED = "Zone Mappings Required"

MESSAGE_SELF_SYSTEM_SIGN_REQUIRED = "Self System Sign Required"
MESSAGE_SELF_SYSTEM_SIGN_IS_BOOLEAN = "Self System Sign Should be Boolean"
MESSAGE_PRIVATE_KEY_REQUIRED = "Private key Required"
MESSAGE_CERTIFICATE_CHAIN_REQUIRED = "Certificate Chain Required"

MESSAGE_PROPERTIES_REQUIRED = "Properties Required"
MESSAGE_LICENSE_FEATURES_REQUIRED = "License features Required"
MESSAGE_NAMESPACE_ADMIN_REQUIRED = "Namespace Admin Required"
