"""
Created on Jun 24, 2015

@author: joshia7
"""

# class URLConstants(object):
"""
Contains all URL
"""

LOGIN = "/login"
LOGOUT = "/logout"

NAMESPACES = "/object/namespaces"
NAMESPACES_DETAILED = "/object/namespaces/namespace/{0}"
UPDATE_NAMESPACE = "/object/namespaces/namespace/{0}"
GET_RETENTION_CLASS = "/object/namespaces/namespace/{0}/retention/{1}"
GET_RETENTION_LIST = "/object/namespaces/namespace/{0}/retention"
GET_NAMESPACE_QUOTA = "/object/namespaces/namespace/{0}/quota"
REMOVE_NAMESPACE_QUOTA = "/object/namespaces/namespace/{0}/quota"

CREATE_NAMESPACE = "/object/namespaces/namespace"
REMOVE_NAMESPACE = "/object/namespaces/namespace/{0}/deactivate"
CREATE_RETENTION = "/object/namespaces/namespace/{0}/retention"
UPDATE_RETENTION = "/object/namespaces/namespace/{0}/retention/{1}"
UPDATE_NAMESPACE_QUOTA = "/object/namespaces/namespace/{0}/quota"

GET_BILLING_NAMESPACE_BUCKET = "/object/billing/buckets/{0}/{1}/info"
GET_BILLING_WITH_INTERVAL = "/object/billing/buckets/{0}/{1}/sample"
GET_BILLING_FOR_NAMESPACE = "/object/billing/namespace/{0}/info"
GET_BILLING_NAMESPACE_WITH_INTERVAL = "/object/billing/namespace/{0}/sample"

GET_CAS_SECRET_KEY = "/object/user-cas/secret/{0}"
GET_CAS_SECRET_WITH_NAMESPACE = "/object/user-cas/secret/{0}/{1}"
UPDATE_CAS_SECRET = "/object/user-cas/secret/{0}"
GET_PROFILE_PEA = "/object/user-cas/secret/{0}/{1}/pea"
DELETE_CAS_SECRET = "/object/user-cas/secret/{0}/deactivate"
GET_DEFAULT_BUCKET_WITH_NAMESPACE = "/object/user-cas/bucket/{0}/{1}"
GET_DEFAULT_BUCKET_FOR_UID = "/object/user-cas/bucket/{0}"
UPDATE_DEFAULT_BUCKET_WITH_NAMESPACE = "/object/user-cas/bucket/{0}/{1}"
REGISTER_CAS_FOR_NAMESPACE = "/object/user-cas/applications/{0}"
UPDATE_CAS_REGISTERED_APPLICATION = "/object/user-cas/metadata/{0}/{1}"
GET_CAS_USER_METADATA = "/object/user-cas/metadata/{0}/{1}"

GET_CERTIFICATE_CHAIN_CONFIGURED = "/object-cert/keystore"
GET_PROPERTIES = "/config/object/properties/"
GET_PROPERTY_METADATA = "/config/object/properties/metadata/"
GET_LICENSE_INFORMATION = "/license"

GET_CAPACITY = "/object/capacity"
GET_CLUSTER_CAPACITY = "/object/capacity/{0}"

GET_LOCAL_VDS_DETAILS = "/dashboard/zones/localzone"
GET_LOCAL_VDC_REPLICATION_GROUPS = "/dashboard/zones/localzone/replicationgroups"
GET_LOCAL_REPLICATION_FAILED_LINKS = "/dashboard/zones/localzone/rglinksFailed"
GET_LOCAL_VDC_STORAGE_DETAILS = "/dashboard/zones/localzone/storagepools"
GET_LOCAL_ZONE_NODES = "/dashboard/zones/localzone/nodes"
GET_STORAGE_POOL_DETAILS = "/dashboard/storagepools/{0}"
GET_NODE_INSTANCE_DETAILS = "/dashboard/nodes/{0}"
GET_DISK_INSTANCE_DETAILS = "/dashboard/disks/{0}"
GET_PROCESS_INSTANCE_DETAILS = "/dashboard/processes/{0}"
GET_NODE_INSTANCE_PROCESS_DETAILS = "/dashboard/nodes/{0}/processes"
GET_NODE_INSTANCE_DISK_DETAILS = "/dashboard/nodes/{0}/disks"
GET_STORAGE_POOL_NODE_DETAILS = " /dashboard/storagepools/{0}/nodes"
GET_VDC_REPLICATION_BOOTSTRAP_DETAILS = "/dashboard/zones/localzone/rglinksBootstrap"
GET_REPLICATION_GROUPS_INSTANCE_DETAILS = "/dashboard/replicationgroups/{0}"
GET_REPLICATION_GROUPS_LINK_INSTANCE_DETAILS = "/dashboard/rglinks/{0}"
GET_REPLICATION_GROUP_INSTANCE_ASSOCIATED_LINK_DETAILS = "/dashboard/replicationgroups/{0}/rglinks"

GET_AUDIT_EVENTS = "/vdc/events"

GET_REPLICATION_GROUPS = "/vdc/data-service/vpools"
GET_SPECIFIED_REPLICATION_GROUP = "/vdc/data-service/vpools/{0}"
UPDATE_REPLICATION_GROUP = "/vdc/data-service/vpools/{0}"
ADD_STORAGE_POOL = "/vdc/data-service/vpools/{0}/addvarrays"
DELETE_STORAGE_POOL = "/vdc/data-service/vpools/{0}/removevarrays"
DELETE_REPLICATION_GROUP = "/vdc/data-service/vpools/{0}/deactivate"
CREATE_REPLICATION_GROUP = "/vdc/data-service/vpools"
REMOVE_FROM_REPLICATION_GROUP = " /vdc/data-service/vpools/{0}/removevarrays"
REMOVE_REPLICATION_GROUP = "/vdc/data-service/vpools/{0}/deactivate"

GET_ALL_TEMP_FAILED_ZONE = "/tempfailedzone/allfailedzones"
GET_FAILED_ZONE_FOR_REPLICATION_GROUPS = "/tempfailedzone/rgid/{0}"

CREATE_BASE_URL = "/object/baseurl"
DELETE_BASE_URL = "/object/baseurl/{0}/deactivate"
UPDATE_BASE_URL = "/object/baseurl/{0}"
GET_SPECIFIED_BASE_URL_DETAILS = "/object/baseurl/{0}"
GET_ALL_BASE_URL = "/object/baseurl"

CREATE_ALERT = "/vdc/callhome/alert/"
CONFIGURE_FTPS_PROPERTIES = "/vdc/callhome/connectemc/config/ftps/"
CONFIGURE_SMTP = "/vdc/callhome/connectemc/config/email/"
DISABLE_CONNECTEMC = "/vdc/callhome/connectemc/config/deactivate"
GET_CONNECTEMC_CONFIG_DETAILS = "/vdc/callhome/connectemc/config"

CREATE_BUCKET = "/object/bucket"
DELETE_BUCKET = "/object/bucket/{0}/deactivate"
GET_BUCKET = "/object/bucket"
UPDATE_RETENTION_PERIOD_FOR_BUCKET = "/object/bucket/{0}/retention"
GET_RETENTION_PERIOD_FOR_BUCKET = "/object/bucket/{0}/retention"
GET_BUCKET_INFORMATION_FOR_BUCKET = "/object/bucket/{0}/info"
UPDATE_BUCKET_OWNER = "/object/bucket/{0}/owner"
UPDATE_IS_STALE_ALLOWED = "/object/bucket/{0}/isstaleallowed"
GET_BUCKET_LOCK = "/object/bucket/{0}/lock"
UP_DATE_BUCKET_LOCK = "/object/bucket/{0}/lock/{1}"
UPDATE_BUCKET_QUOTA = "/object/bucket/{0}/quota"
GET_BUCKET_QUOTA = "/object/bucket/{0}/quota"
DELETE_QUOTA = "/object/bucket/{0}/quota"
UPDATE_ACL = "/object/bucket/{0}/acl"
GET_ACL = "/object/bucket/{0}/acl"
GET_ACL_PERMISSION = "/object/bucket/acl/permissions"
GET_ACL_GROUPS = "/object/bucket/acl/groups"
GET_VDC_DATA_STORES = "/vdc/data-stores"
CREATE_DATA_STORE = "/vdc/data-stores/commodity"
GET_COMMODITY_DATA_STORE_WITH_STORAGE_POOL = "/vdc/data-stores/commodity/{0}"
GET_COMMODITY_DATA_STORE_WITH_VARRAY = "/vdc/data-stores/commodity/search/varray/{0}"
DEACTIVATE_DATA_STORE = "/vdc/data-stores/{0}/deactivate"
LIST_SPECIFIC_TASK = "/vdc/data-stores/{0}/tasks/{1}/"
GET_BULK_RESOURCES = "/vdc/data-stores/bulk"
GET_DATA_NODES = "/vdc/nodes"
CREATE_STORAGE_POOL = "/vdc/data-services/varrays"
DELETE_VARRAY = "/vdc/data-services/varrays/{0}"
UPDATE_VARRAY = "/vdc/data-services/varrays/{0}"
GET_DETAILS_STORAGE_POOL = "/vdc/data-services/varrays/{0}"
GET_LIST_OF_STORAGE_POOLS = "/vdc/data-services/varrays"

INSERT_VDC_ATTRIBUTES = "/object/vdcs/vdc/{0}"
DEACTIVATE_AND_DELETE_VDC = "/object/vdcs/vdc/{0}/deactivate"
GET_VDC_BY_NAME = "/object/vdcs/vdc/{0}"
GET_VDC_BY_ID = "/object/vdcs/vdcid/{0}"
GET_VDC_LOCAL_DETAILS = "/object/vdcs/vdc/local"
GET_VDC_SECRET_KEY = "/object/vdcs/vdc/local/secretkey"
GET_VDC_LIST = "/object/vdcs/vdc/list"

GET_SPECIFIED_AUTHENTICATION_PROVIDER = "/vdc/admin/authnproviders/{0}"
GET_AUTHENTICATION_PROVIDER_LIST = "/vdc/admin/authnproviders"
CREATE_AUTHENTICATION_PROVIDER = "/vdc/admin/authnproviders"
UPDATE_AUTHENTICATION_PROVIDER = "/vdc/admin/authnproviders/{0}"
DELETE_AUTHENTICATION_PROVIDER = "/vdc/admin/authnproviders/{0}"

GET_USER_GROUPS = "/object/user-password/{0}"
GET_ALL_USER_GROUPS = "/object/user-password/{0}/{1}"
CREATE_PASSWORD = "/object/user-password/{0}"
UPDATE_PASSWORD = "/object/user-password/{0}"
DELETE_PASSWORD_GROUP = "/object/user-password/{0}/deactivate"

GET_KEYS_FOR_USER = "/object/user-secret-keys/{0}"
GET_ALL_KEY_FOR_USER = "/object/user-secret-keys/{0}/{1}"
CREATE_NEW_KEY = "/object/user-secret-keys/{0}"
DELETE_USER_KEY = "/object/user-secret-keys/{0}/deactivate"

GET_ALL_SECRET_KEYS = "/object/secret-keys"
CREATE_SECRET_KEY = "/object/secret-keys"
DELETE_SECRET_KEY = "/object/secret-keys/deactivate"

CREATE_LOCAL_VDC_USER_INFO = "/vdc/users"
DELETE_LOCAL_VDC_USER_INFO = "/vdc/users/{0}/deactivate"
UPDATE_LOCAL_VDC_USER_INFO = "/vdc/users/{0}"
GET_LOCAL_VDC_USER_INFO = "/vdc/users/{0}"
LIST_LOCAL_VDC_USERS = "/vdc/users"

CREATE_USER_FOR_NAMESPACE = "/object/users"
DELETE_SPECIFIED_USER = "/object/users/deactivate"
GET_USER_DETAILS = "/object/users/{0}/info"
GET_USER_IDENTIFIERS = "/object/users"
GET_USER_IDENTIFIERS_FOR_NAMESPACE = " /object/users/{0}"
LOCK_SPECIFIED_USER = "/object/users/lock"
GET_LOCK_DETAILS_FOR_USER_NAMESPACE = "/object/users/lock/{0}/{1}"
GET_LOCK_FOR_USER = "/object/users/lock/{0}"

SET_KEY_CERTIFICATE_PAIR = "/object-cert/keystore"

SET_PROPERTIES = "/config/object/properties/"

ADD_LICENSE = "/license.json"

# GET_ALL_USERS = "/object/users"
#     GET_SPECIFIED_USER = "/object/users/{0}/info"
#     GET_USER_FOR_NAMESPACE = "/object/users/{0}"
#     GET_LOCK_DETAILS_FOR_USER_NAMESPACE = "/object/users/lock/{0}/{1}"
#     GET_LOCK_FOR_USER = "/object/users/lock/{0}"
